version: '3'

services:
  api:
    build: .
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - EXPRESS_PORT=${EXPRESS_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - CLOUD_NAME=${CLOUD_NAME}
      - API_KEY=${API_KEY}
      - API_SECRET=${API_SECRET}
    volumes:
      - .:/usr/src/app
